ENH: datetime64: support AC dates starting with '+'
Numpy allows negatives signs but throws a value error when parsing
datetime strings starting with '+':
>>> np.datetime64('+1000-01-01T00:00:00Z')
ValueError: Error parsing datetime string "+1000-01-01T00:00:00Z" at position 0

Since the default is positive years, we just need to skip the '+'
character.

Fixes #10810.