TST: fix test errors for Pathlib usage tests in io.py.
Pathlib was only added to the stdlib in Python 3.4, and there it
can handle string type input for a file with UTF8 encoding.
But the Patlib version on PyPi that can be installed for Python 2.7
doesn't accept strings, gives errors like:

    ======================================================================
    ERROR: test_ndfromtxt (test_io.TestPathUsage)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/rgommers/Code/numpy/numpy/testing/decorators.py", line 147, in skipper_func
        return f(*args, **kwargs)
      File "/home/rgommers/Code/numpy/numpy/lib/tests/test_io.py", line 1888, in test_ndfromtxt
        f.write('1 2\n3 4')
    TypeError: must be unicode, not str