BUG: Fix crash in error message formatting introduced by gh-11230
Fixes gh-11221, and now produces:

```python
>>> a = np.ones((3, 3, 4, 5, 6))
>>> b = np.ones((3, 4, 5))
>>> np.einsum('aabcb,abc', a, b)
ValueError: dimensions in operand 0 for collapsing index 'b' don't match (4 != 6)
```