BUG: Make np.partition and np.sort work on np.matrix when axis=None
Both were making the normally valid assumption that flatten actually flattens, which turns out to be false for matrices.

Old behavior:

>>> a = np.matrix([[1, 2, 0]])
>>> np.partition(a, 1, axis=None)
ValueError: kth(=1) out of bounds (1)
>>> np.sort(a, axis=None)
matrix([[1, 2, 0]])