BUG: Fix thinko in assert_deprecated()
assert_deprecated() was recently reworked for stylistic changes (in
0aa32608 "STY: Minor style cleanups in tests and C code.") but made a
thinko - `lst` is already a list of warnings, so we don't need to put
that into [] braces when preparing assertion text. If we do the
reporting breaks:

    In [1]: msg = "4 warnings found but 3 expected."
    In [2]: lst = ['CategoryA', 'CategoryB', 'CategoryC']
    In [3]: n.join([msg] + [lst])
    TypeError   Traceback (most recent call last)
    ----> 1 n.join([msg] + [lst])

    TypeError: sequence item 1: expected string, list found

Fix it.

Cc: Charles Harris <charlesr.harris@gmail.com>