Revert "Merge pull request #3567 from arinkverma/avoid_conversion"
This reverts commit de9f1c92d3ca0920bce915438f0406f587aa98db, reversing
changes made to d958dec676beeac218a118fac084fa8b14bc9171.

There is a change of behavior in conversion of signed to unsigned
PyLong that shows up on my machine. For some reason this did not show
up in the travisbot tests. This reverts the merge that led to this
problem until it can be sorted out. Error shows up as

numpy/core/arrayprint.py",
line 653, in __call__
    if _MININT < x < _MAXINT:
OverflowError: can't convert negative int to unsigned